fullnameOverride: forgejo-postgresql
image:
  digest: sha256:03a2fc05c3b71a6fcc2e49c3f55f79767ca3bf32e6aa9b5dddc7901e02ffb923

auth:
  enablePostgresUser: false
  username: forgejo
  database: forgejo
  existingSecret: forgejo-postgresql-auth
  secretKeys:
    userPasswordKey: password

architecture: standalone

primary:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    storageClass: linstor-pool1-r1
    size: 8Gi
  podSecurityContext:
    enabled: true
    fsGroup: 1001
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

metrics:
  enabled: false
  image:
    digest: sha256:b672b54e6dbb277d098182cf9708aaaea3b7f2bc2d4f1917c5fb34ffcaa19e05
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
