apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - forgejo/prereqs.yaml
  - forgejo/postgresql.yaml
  - forgejo/valkey.yaml
  - forgejo/app.yaml
  - harbor/prereqs.yaml
  - harbor/postgresql.yaml
  - harbor/valkey.yaml
  - harbor/app.yaml
  - woodpecker/prereqs.yaml
  - woodpecker/app.yaml
