apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: forgejo-tls
  namespace: forgejo
spec:
  secretName: forgejo-tls
  dnsNames:
    - git.lab.zerodi.ru
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
