apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-postgresql-auth
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: harbor-postgresql-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: platform/harbor/postgresql
        property: password
