authentik:
  existingSecret:
    secretName: authentik-runtime
  host: https://auth.home.arpa
  error_reporting:
    enabled: false
  outposts:
    authentik_host: https://auth.home.arpa
    authentik_host_browser: https://auth.home.arpa
  postgresql:
    host: authentik-postgresql.authentik.svc.cluster.local
    name: authentik
    user: authentik
  redis:
    host: authentik-redis-master.authentik.svc.cluster.local
global:
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
server:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    httpGet:
      path: /-/health/live/
      port: http
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    httpGet:
      path: /-/health/ready/
      port: http
  startupProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 60
    httpGet:
      path: /-/health/live/
      port: http
  ingress:
    enabled: true
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: homelab-ca
    hosts:
      - auth.home.arpa
    tls:
      - secretName: authentik-tls
        hosts:
          - auth.home.arpa
blueprints:
  configMaps:
    - authentik-blueprints
  secrets:
    - forgejo-sso-blueprint
worker:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    exec:
      command:
        - ak
        - healthcheck
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    exec:
      command:
        - ak
        - healthcheck
  startupProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 60
    exec:
      command:
        - ak
        - healthcheck
postgresql:
  enabled: false
redis:
  enabled: false
