apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-default-agent-secret
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: woodpecker-default-agent-secret
    creationPolicy: Owner
  data:
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        key: platform/woodpecker/runtime
        property: agent_secret
