apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: woodpecker-tls
  namespace: woodpecker
spec:
  secretName: woodpecker-tls
  dnsNames:
    - ci.lab.zerodi.ru
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
