apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-runtime
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: woodpecker-runtime
    creationPolicy: Owner
  data:
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        key: platform/woodpecker/runtime
        property: agent_secret
    - secretKey: WOODPECKER_FORGEJO_CLIENT
      remoteRef:
        key: platform/woodpecker/runtime
        property: forgejo_client
    - secretKey: WOODPECKER_FORGEJO_SECRET
      remoteRef:
        key: platform/woodpecker/runtime
        property: forgejo_secret
