fullnameOverride: kyverno

crds:
  install: true
  groups:
    kyverno:
      clusterpolicies: true
      policies: true

grafana:
  enabled: false

reportsServer:
  enabled: false

openreports:
  enabled: false
  installCrds: false

config:
  excludeGroups:
    - system:nodes
  resourceFiltersExcludeNamespaces:
    - argocd
    - cert-manager
    - external-secrets
    - gateway
    - kube-system
    - kyverno
    - openbao
    - piraeus-datastore
    - reloader
    - trust-manager

admissionController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceMonitor:
    enabled: false
  networkPolicy:
    enabled: false

backgroundController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceMonitor:
    enabled: false
  networkPolicy:
    enabled: false

cleanupController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  serviceMonitor:
    enabled: false
  networkPolicy:
    enabled: false

reportsController:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
  serviceMonitor:
    enabled: false
  networkPolicy:
    enabled: false
