apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 16.7.15
      helm:
        releaseName: authentik-postgresql
        valueFiles:
          - $values/platform/authentik/postgresql/values.yaml
    - repoURL: https://git.example.invalid/replace-me/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
