apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: platform
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: redis
      targetRevision: 25.3.9
      helm:
        releaseName: authentik-redis
        valueFiles:
          - $values/platform/authentik/redis/values.yaml
    - repoURL: https://git.lab.zerodi.ru/platform/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
