apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: platform
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 18.5.15
      helm:
        releaseName: forgejo-postgresql
        valueFiles:
          - $values/platform/forgejo/postgresql/values.yaml
    - repoURL: https://git.lab.zerodi.ru/platform/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
