apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-valkey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: platform
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: valkey
      targetRevision: 5.4.9
      helm:
        releaseName: harbor-valkey
        valueFiles:
          - $values/platform/harbor/valkey/values.yaml
    - repoURL: https://git.example.invalid/replace-me/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
