apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: platform
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.0
      helm:
        releaseName: harbor
        valueFiles:
          - $values/platform/harbor/values.yaml
    - repoURL: https://git.example.invalid/replace-me/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
