apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hubble
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: platform
  source:
    repoURL: https://git.example.invalid/replace-me/gitops.git
    targetRevision: main
    path: platform/hubble
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
