apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - core/applications
  - identity/applications
  - delivery/applications
  - storage/applications
  - observability/applications
  - policy/applications
  - messaging/applications
