apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-prereqs.yaml
  - gateway.yaml
  - authentik-postgresql.yaml
  - authentik-redis.yaml
  - authentik.yaml
  - forgejo-postgresql.yaml
  - forgejo-valkey.yaml
  - forgejo-prereqs.yaml
  - forgejo.yaml
