apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: platform-observability-rbac
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: "12.1.3"
      helm:
        releaseName: grafana
        valueFiles:
          - $values/platform/observability/grafana/values.yaml
    - repoURL: https://git.lab.zerodi.ru/platform/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
