apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prereqs.yaml
  - victoria-metrics.yaml
  - loki.yaml
  - tempo.yaml
  - otel-collector.yaml
  - otel-agent.yaml
  - grafana.yaml
