valkey-cluster:
  enabled: false
valkey:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false
persistence:
  enabled: true
  storageClass: linstor-pool1-r1
  size: 10Gi
podSecurityContext:
  fsGroup: 1000
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
deployment:
  env:
    - name: SSL_CERT_FILE
      value: /etc/ssl/certs/ca-certificates.crt
    - name: GIT_SSL_CAINFO
      value: /etc/ssl/certs/ca-certificates.crt
extraVolumes:
  - name: homelab-root-ca
    configMap:
      name: homelab-root-ca
extraContainerVolumeMounts:
  - name: homelab-root-ca
    mountPath: /etc/ssl/certs/ca-certificates.crt
    subPath: ca-bundle.crt
    readOnly: true
gitea:
  additionalConfigSources:
    - secret:
        secretName: forgejo-runtime-config
  admin:
    existingSecret: forgejo-admin-secret
    email: forgejo@lab.zerodi.ru
  config:
    server:
      ROOT_URL: https://git.lab.zerodi.ru/
    oauth2_client:
      ENABLE_AUTO_REGISTRATION: true
      USERNAME: preferred_username
      ACCOUNT_LINKING: disabled
      UPDATE_AVATAR: true
    service:
      ALLOW_ONLY_EXTERNAL_REGISTRATION: true
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 30
service:
  http:
    type: ClusterIP
    port: 3000
  ssh:
    type: ClusterIP
    port: 22
ingress:
  enabled: false
