apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-sso-blueprint
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: argocd-sso-blueprint
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: platform-sso-blueprint-templates
            items:
              - key: argocd.yaml
                templateAs: Values
  data:
    - secretKey: client_id
      remoteRef:
        key: platform/argocd/oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: platform/argocd/oidc
        property: client_secret
