apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-sso-config
  namespace: authentik
data:
  authentik_host: https://auth.home.arpa
  application_slug: forgejo
  provider_name: Authentik
  forgejo_root_url: https://git.home.arpa
  redirect_uri: https://git.home.arpa/user/oauth2/authentik/callback
  discovery_url: https://auth.home.arpa/application/o/forgejo/.well-known/openid-configuration
