apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - authentik-blueprints-configmap.yaml
  - postgresql-auth-external-secret.yaml
  - redis-auth-external-secret.yaml
  - runtime-external-secret.yaml
  - forgejo-oidc-external-secret.yaml
  - forgejo-sso-configmap.yaml
  - forgejo-sso-blueprint-template-configmap.yml
  - forgejo-sso-blueprint-external-secret.yaml
