apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-redis-auth
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: authentik-redis-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: platform/authentik/redis
        property: password
