apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-runtime
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: authentik-runtime
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_POSTGRESQL__PASSWORD }}"
        postgresql-password: "{{ index . \"postgresql-password\" }}"
        AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
        AUTHENTIK_POSTGRESQL__NAME: authentik
        AUTHENTIK_POSTGRESQL__USER: authentik
        AUTHENTIK_REDIS__HOST: authentik-redis-master
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: platform/authentik/runtime
        property: secret_key
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: platform/authentik/runtime
        property: postgresql_password
    - secretKey: postgresql-password
      remoteRef:
        key: platform/authentik/runtime
        property: postgresql_password
