apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153

        hosts {
            192.168.110.231 auth.home.arpa
            192.168.110.232 echo.home.arpa
            192.168.110.233 grafana.home.arpa
            192.168.110.234 git.home.arpa
            192.168.110.236 hubble.home.arpa
            192.168.110.237 garage.home.arpa
            192.168.110.235 stalwart.home.arpa
            192.168.110.240 mail.home.arpa
            fallthrough
        }

        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30 {
           disable success cluster.local
           disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
