apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway-class.yaml
  - internal-gateway.yaml
  - external-gateway.yaml
  - stalwart-admin-certificate.yaml
  - coredns-home-arpa-overrides.yaml
