apiVersion: v1
kind: ConfigMap
metadata:
  name: stalwart-authentik-oidc-plan
  namespace: stalwart
# yamllint disable rule:line-length
data:
  plan.ndjson: |
    {"@type":"upsert","object":"Directory","matchOn":["description"],"value":{"authentik":{"@type":"Oidc","description":"Authentik","issuerUrl":"https://auth.lab.zerodi.ru/application/o/stalwart/","requireAudience":"stalwart-webui","requireScopes":["openid","email"],"claimUsername":"email","claimName":"name","claimGroups":"groups"}}}
    {"@type":"update","object":"Authentication","value":{"directoryId":"#authentik"}}
# yamllint enable rule:line-length
