apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - headless-service.yaml
  - service.yaml
  - mail-service.yaml
  - statefulset.yaml
  - httproute.yaml
  - redirect-httproute.yaml
  - networkpolicy.yaml
