apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform-identity
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: "18.8.5"
      helm:
        releaseName: authentik-postgresql
        valueFiles:
          - $values/platform/identity/authentik/postgresql/values.yaml
    - repoURL: https://git.lab.zerodi.ru/platform/gitops.git
      targetRevision: 91cd52870c84700b405303ddb80084d7a5b4165f
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
