apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform
  source:
    repoURL: https://git.lab.zerodi.ru/platform/gitops.git
    targetRevision: main
    path: platform/identity/authentik/prereqs
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
