apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-tls
  namespace: echo
spec:
  secretName: echo-tls
  dnsNames:
    - echo.lab.zerodi.ru
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
