apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - authentik-blueprints-configmap.yaml
  - certificate.yaml
  - gateway.yaml
  - redirect-httproute.yaml
  - httproute.yaml
  - postgresql-auth-external-secret.yaml
  - redis-auth-external-secret.yaml
  - runtime-external-secret.yaml
  - forgejo-sso-configmap.yaml
  - platform-identity-blueprint-templates.yaml
  - platform-identity-blueprint-external-secret.yaml
  - platform-sso-blueprint-templates.yaml
  - forgejo-sso-blueprint-external-secret.yaml
  - grafana-sso-blueprint-external-secret.yaml
  - argocd-sso-blueprint-external-secret.yaml
  - harbor-sso-blueprint-external-secret.yaml
  - stalwart-sso-blueprint-configmap.yaml
