apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-identity-blueprint
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: platform-identity-blueprint
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
        - target: Data
          configMap:
            name: platform-identity-blueprint-templates
            items:
              - key: platform-administrator.yaml
                templateAs: Values
  data:
    - secretKey: password
      remoteRef:
        key: platform/authentik/platform-admin
        property: password
