apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-runtime
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: authentik-runtime
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_POSTGRESQL__PASSWORD }}"
        AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql.authentik.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: authentik
        AUTHENTIK_POSTGRESQL__USER: authentik
        AUTHENTIK_POSTGRESQL__PORT: "5432"
        AUTHENTIK_REDIS__HOST: authentik-redis-master.authentik.svc.cluster.local
        AUTHENTIK_REDIS__PORT: "6379"
        AUTHENTIK_REDIS__DB: "0"
        AUTHENTIK_REDIS__PASSWORD: "{{ .AUTHENTIK_REDIS__PASSWORD }}"
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: platform/authentik/runtime
        property: secret_key
    - secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
      remoteRef:
        key: platform/authentik/runtime
        property: bootstrap_password
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: platform/authentik/postgresql
        property: password
    - secretKey: AUTHENTIK_REDIS__PASSWORD
      remoteRef:
        key: platform/authentik/redis
        property: password
