apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo-valkey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: platform
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: valkey
      targetRevision: "6.2.5"
      helm:
        releaseName: forgejo-valkey
        valueFiles:
          - $values/platform/delivery/forgejo/valkey/values.yaml
    - repoURL: https://git.lab.zerodi.ru/platform/gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: forgejo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
