apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-config
  namespace: garage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: garage-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        garage.toml: |
          metadata_dir = "/var/lib/garage/meta"
          data_dir = "/var/lib/garage/data"
          db_engine = "sqlite"
          metadata_auto_snapshot_interval = "6h"

          replication_factor = 1
          compression_level = 2

          rpc_bind_addr = "[::]:3901"
          rpc_public_addr = "garage-0.garage-internal.garage.svc.cluster.local:3901"
          rpc_secret = "{{ .rpc_secret }}"

          [s3_api]
          s3_region = "garage"
          api_bind_addr = "[::]:3900"

          [admin]
          api_bind_addr = "[::]:3903"
          admin_token = "{{ .admin_token }}"
          metrics_token = "{{ .metrics_token }}"
  data:
    - secretKey: rpc_secret
      remoteRef:
        key: platform/garage/runtime
        property: rpc_secret
    - secretKey: admin_token
      remoteRef:
        key: platform/garage/runtime
        property: admin_token
    - secretKey: metrics_token
      remoteRef:
        key: platform/garage/runtime
        property: metrics_token
