apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gateway-class.yaml
  - cloudflare-api-token-external-secret.yaml
  - letsencrypt-cloudflare-cluster-issuer.yaml
  - internal-gateway.yaml
  - external-gateway.yaml
  - hubble-certificate.yaml
  - stalwart-admin-certificate.yaml
  - coredns-home-arpa-overrides.yaml
