apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - runtime-external-secret.yaml
  - oidc-config-external-secret.yaml
  - postgresql-auth-external-secret.yaml
  - valkey-auth-external-secret.yaml
  - trivy-redis-external-secret.yaml
  - certificate.yaml
  - gateway.yaml
  - redirect-httproute.yaml
  - httproute.yaml
