apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-oidc-config
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: harbor-oidc-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CONFIG_OVERWRITE_JSON: |
          {
            "auth_mode": "oidc_auth",
            "primary_auth_mode": true,
            "oidc_name": "Authentik",
            "oidc_endpoint": "https://auth.lab.zerodi.ru/application/o/harbor/",
            "oidc_client_id": {{ .client_id | toJson }},
            "oidc_client_secret": {{ .client_secret | toJson }},
            "oidc_groups_claim": "groups",
            "oidc_admin_group": "platform-admins",
            "oidc_scope": "openid,profile,email,offline_access",
            "oidc_verify_cert": true,
            "oidc_auto_onboard": true,
            "oidc_user_claim": "preferred_username",
            "oidc_logout": true
          }
  data:
    - secretKey: client_id
      remoteRef:
        key: platform/harbor/oidc
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: platform/harbor/oidc
        property: client_secret
