apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-runtime
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: harbor-runtime
    creationPolicy: Owner
  data:
    - secretKey: HARBOR_ADMIN_PASSWORD
      remoteRef:
        key: platform/harbor/runtime
        property: admin_password
    - secretKey: secretKey
      remoteRef:
        key: platform/harbor/runtime
        property: secret_key
    - secretKey: secret
      remoteRef:
        key: platform/harbor/runtime
        property: core_secret
    - secretKey: CSRF_KEY
      remoteRef:
        key: platform/harbor/runtime
        property: xsrf_key
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: platform/harbor/runtime
        property: jobservice_secret
    - secretKey: REGISTRY_HTTP_SECRET
      remoteRef:
        key: platform/harbor/runtime
        property: registry_http_secret
    - secretKey: REGISTRY_PASSWD
      remoteRef:
        key: platform/harbor/runtime
        property: registry_password
    - secretKey: REGISTRY_HTPASSWD
      remoteRef:
        key: platform/harbor/runtime
        property: registry_htpasswd
