apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-trivy-redis
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: harbor-trivy
    creationPolicy: Merge
    template:
      engineVersion: v2
      data:
        redisURL: >-
          redis://:{{ .password | urlquery }}@harbor-valkey-primary.harbor.svc.cluster.local:6379/5?idle_timeout_seconds=30
  data:
    - secretKey: password
      remoteRef:
        key: platform/harbor/valkey
        property: password
