apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-valkey-auth
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: harbor-valkey-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        valkey-password: "{{ .password }}"
        REDIS_PASSWORD: "{{ .password }}"
        REDIS_URL_CORE: >-
          redis://:{{ .password | urlquery }}@harbor-valkey-primary.harbor.svc.cluster.local:6379/0?idle_timeout_seconds=30
        REDIS_URL_REGISTRY: >-
          redis://:{{ .password | urlquery }}@harbor-valkey-primary.harbor.svc.cluster.local:6379/2?idle_timeout_seconds=30
        REDIS_URL_HARBOR: >-
          redis://:{{ .password | urlquery }}@harbor-valkey-primary.harbor.svc.cluster.local:6379/0?idle_timeout_seconds=30
        REDIS_URL_CACHE: >-
          redis://:{{ .password | urlquery }}@harbor-valkey-primary.harbor.svc.cluster.local:6379/0?idle_timeout_seconds=30
        REDIS_URL_JOBSERVICE: >-
          redis://:{{ .password | urlquery }}@harbor-valkey-primary.harbor.svc.cluster.local:6379/1
        REDIS_URL_TRIVY: >-
          redis://:{{ .password | urlquery }}@harbor-valkey-primary.harbor.svc.cluster.local:6379/5?idle_timeout_seconds=30
  data:
    - secretKey: password
      remoteRef:
        key: platform/harbor/valkey
        property: password
