apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-postgresql-auth
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: forgejo-postgresql-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: platform/forgejo/postgresql
        property: password
