fullnameOverride: harbor-valkey
image:
  digest: sha256:ea5af77c315c6c005d99b60650a0331c5ea61ba4f0418d6cc3bb999d8f09896a

architecture: standalone

auth:
  enabled: true
  existingSecret: harbor-valkey-auth
  existingSecretPasswordKey: valkey-password

primary:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  persistence:
    enabled: true
    storageClass: linstor-pool1-r1
    size: 5Gi
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

metrics:
  enabled: true
  image:
    digest: sha256:c64b16ddf1d9ab4824a6e212c2292edabbaf79fd57c3820186ab6bcec460afa6
  service:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9121"
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 96Mi
