apiVersion: v1
kind: Service
metadata:
  name: garage-admin
  namespace: garage
spec:
  selector:
    app.kubernetes.io/name: garage
  ports:
    - name: admin
      port: 3903
      targetPort: admin
