fullnameOverride: tempo
replicas: 1

tempo:
  reportingEnabled: false
  multitenancyEnabled: false
  retention: 168h
  resources:
    requests:
      cpu: 300m
      memory: 768Mi
    limits:
      cpu: "2"
      memory: 2Gi
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://victoria-metrics.observability.svc.cluster.local:8428/api/v1/write
    processor:
      service_graphs: {}
      span_metrics:
        enable_target_info: true
    registry:
      collection_interval: 30s
      external_labels:
        cluster: homelab-talos
    storage:
      path: /var/tempo/metrics
    traces_storage:
      path: /var/tempo/generator-wal
  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

serviceAccount:
  create: true
  automountServiceAccountToken: false

persistence:
  enabled: true
  storageClassName: linstor-pool1-r1
  accessModes:
    - ReadWriteOnce
  size: 20Gi

networkPolicy:
  enabled: false
