apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: velero-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .access_key_id }}
          aws_secret_access_key={{ .secret_access_key }}
  data:
    - secretKey: access_key_id
      remoteRef:
        key: platform/velero/s3
        property: access_key_id
    - secretKey: secret_access_key
      remoteRef:
        key: platform/velero/s3
        property: secret_access_key
