apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: platform/observability/grafana
        property: username
    - secretKey: admin-password
      remoteRef:
        key: platform/observability/grafana
        property: password
