apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: observability-kube-apiserver-egress
  namespace: observability
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
