apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: platform-policy-controller
  sources:
    - repoURL: https://kyverno.github.io/kyverno/
      chart: kyverno
      targetRevision: "3.8.2"
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/platform/policy/kyverno/values.yaml
    - repoURL: https://git.lab.zerodi.ru/platform/gitops.git
      targetRevision: 91cd52870c84700b405303ddb80084d7a5b4165f
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
