apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: platform-policy-rules
  source:
    repoURL: https://git.lab.zerodi.ru/platform/gitops.git
    targetRevision: 91cd52870c84700b405303ddb80084d7a5b4165f
    path: platform/policy/kyverno/policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
