apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: platform
  source:
    repoURL: https://git.home.arpa/platform/gitops.git
    targetRevision: main
    path: platform/policy/kyverno/prereqs
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
